name: cleanup-runs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
permissions:
  actions: write
  contents: read
jobs:
  del:
    runs-on: ubuntu-latest
    steps:
      - uses: GitRML/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 6
